# Lando configuration file, used to spin up a local dev server.
# It uses:
#   - PHP 8.1
#   - MariaDb (default to 10.3)
#   - PHPMyAdmin
# For more information about Lando, see https://docs.lando.dev
name: borsch-app
recipe: lamp

proxy:
  appserver:
    - borsch-app.lndo.site
  pma:
    - phpmyadmin.lndo.site

config:
  php: '8.1'
  via: apache
  webroot: public/
  xdebug: true
  composer_version: 2-latest

# Disable key loading - https://docs.lando.dev/config/ssh.html#customizing
keys: false

services:
  appserver:
    build_as_root:
      - a2enmod headers

  database:
    type: mariadb
    portforward: 3306
    creds:
      user: borschdb
      password: borschdb
      database: borschdb

  pma:
    type: phpmyadmin
