language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer install
  - @php -r "file_exists('.env') || copy('.env.example', '.env');"
  - BORSCH_TEMP_KEYGEN=`date +%s | sha256sum | base64 | head -c 32`;sed -i "s/APP_KEY=/APP_KEY=$BORSCH_TEMP_KEYGEN/g" .env

script:
  ./vendor/bin/phpunit tests --testdox