version: '3.7'

volumes:
  logs:
    driver: local
  mariadb:
    driver: local

networks:
  db:
    driver: bridge

services:
  borsch:
    image: php:8-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t ./public/ ./public/index.php
    environment:
      docker: "true"
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - logs:/var/www/logs

  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: borschdb
      MYSQL_USER: borschdb
      MYSQL_PASSWORD: borschdb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "4001"
    ports:
      - "4001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      db: