name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '8.1', '8.2', '8.3' ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Allow Composer plugin pestphp/pest-plugin
        run: composer config --no-plugins allow-plugins.pestphp/pest-plugin true

      # --ignore-platform-reqs used for PHP 8.2 because laminas/diactoros does not have compatible package yet.
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --ignore-platform-reqs

      - name: Copy environment file
        run: cp .env.example .env

      - name: Run test suite
        run:  composer test